### ISSUE TITLE
 "kallsyms_lookup_name" undefined!

### ISSUE THREAD

**Issue by pavlinux** [Chester-Gillon/cmem_gdb_access#1]
```
# make
 CC [M]  /tmp/cmem_gdb_access/module/cmem.o
  LD [M]  /tmp/cmem_gdb_access/module/cmem_dev.o
  MODPOST /tmp/cmem_gdb_access/module/Module.symvers
ERROR: modpost: "kallsyms_lookup_name" [/tmp/cmem_gdb_access/module/cmem_dev.ko] undefined!
```
```
# zcat /proc/config.gz | grep KALLSYMS
CONFIG_KALLSYMS=y
CONFIG_KALLSYMS_ALL=y
CONFIG_KALLSYMS_ABSOLUTE_PERCPU=y
CONFIG_KALLSYMS_BASE_RELATIVE=y
```

**Comment by Chester-Gillon** [comment]
Which Linux distribution and Kernel version were you using when the error occurred?

Unfortunately the use of ``kallsyms_lookup_name`` is a bit of a hack as I attempted to describe in my stackoverflow answer in [How can I access the kernel command line from a Linux kernel module?](https://stackoverflow.com/a/76021772/4207678)

The code in question:
1. Compiles and works with the ``4.18.0-513.18.1.el8_9.x86_64`` Kernel  provided by AlmaLinux 8.9
2. With the ``5.15.0-105-generic`` Kernel provided by  Ubuntu 22.04.4 LTS results in an error that ``kallsyms_lookup_name`` is undefined.

**Comment by pavlinux** [comment]
https://lwn.net/Articles/813350/
